"""Build portable Builder records from the Callus storefront source files."""
import json
from pathlib import Path

APP = Path(__file__).resolve().parents[1]
DEST = APP / 'builder_files'
RELEASE = json.loads((APP / 'callus_storefront/release.json').read_text())
ICON = '<svg class="cg-icon" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.5">{}</svg>'
arrow=ICON.format('<path d="M4 12h15m-6-6 6 6-6 6"/>')
search=ICON.format('<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>')
heart=ICON.format('<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>')
bag=ICON.format('<path d="M5 7h14l1 14H4L5 7Z M9 8V6a3 3 0 0 1 6 0v2"/>')
user=ICON.format('<circle cx="12" cy="8" r="3.5"/><path d="M5 21v-2a7 7 0 0 1 14 0v2"/>')
leaf=ICON.format('<path d="M20 3C8 2 2 8 5 15c4 8 16 2 15-12ZM3 21 15 9"/>')
truck=ICON.format('<path d="M2 5h12v12H2z M14 10h5l3 4v3h-8"/><circle cx="6" cy="18" r="2"/><circle cx="18" cy="18" r="2"/>')
location=ICON.format('<path d="M19 10c0 6-7 12-7 12S5 16 5 10a7 7 0 0 1 14 0Z"/><circle cx="12" cy="10" r="2.5"/>')
nav=[('Indoor plants','/category/indoor'),('Outdoor plants','/category/outdoor'),('Pots & planters','/category/pots'),('Grow your own','/category/grow'),('Soil & plant care','/category/care'),('Tools & watering','/category/tools'),('Flowers & gifts','/categories'),('Customer favourites','/collection/popular')]
searchform=f'<form class="cg-search" role="search" action="/store"><input type="search" name="q" placeholder="Find your next plant, pot or little joy…" aria-label="Search products" maxlength="100"><button aria-label="Search" type="submit">{search}</button></form>'
header=f'''<a class="cg-skip" href="#cg-main">Skip to content</a><div class="cg-announcement">A LITTLE GREENER. A LITTLE HAPPIER. &nbsp; · &nbsp; CALLUS GARDEN CENTRE, MALTA</div><header class="cg-header"><div class="cg-wrap"><div class="cg-head-main"><button class="cg-menu-button" aria-label="Open menu" aria-expanded="false" aria-controls="cg-mobile-menu" data-menu-toggle>{ICON.format('<path d="M3 6h18M3 12h18M3 18h18"/>')}</button><a class="cg-brand" href="/shop" aria-label="Callus Garden Centre home"><img class="cg-logo" src="/assets/webshop/callus/callus-logo.png" alt="Callus Garden Centre" width="237" height="183" fetchpriority="high"></a>{searchform}<div class="cg-actions"><a class="cg-icon-link cg-account-link" href="/account-callus" aria-label="My account">{user}<span class="cg-action-label">Account</span></a><a class="cg-icon-link" href="/saved" aria-label="Saved favourites">{heart}</a><a class="cg-icon-link" href="/cart" aria-label="Your basket">{bag}<span class="cg-bag-count" data-basket-count>0</span></a></div></div><nav class="cg-nav" aria-label="Main navigation">{''.join(f'<a href="{url}" class="'+('cg-nav-accent' if i==7 else '')+f'">{title}</a>' for i,(title,url) in enumerate(nav))}</nav></div><div class="cg-mobile-search">{searchform}</div><nav class="cg-mobile-drawer" id="cg-mobile-menu" aria-label="Mobile navigation">{''.join(f'<a href="{url}">{title}</a>' for title,url in nav)}<a href="/account-callus">My account</a><a href="/contact-callus">Visit & contact us</a></nav></header>'''
footer='''<footer class="cg-footer"><div class="cg-wrap"><div class="cg-footer-main"><div><p class="cg-footer-brand">Let good things grow.</p><p>Plants, pots and everyday inspiration for a greener home and garden. From Callus Garden Centre, with care.</p></div><div><h3>Explore</h3><ul><li><a href="/store">Shop all products</a></li><li><a href="/categories">Shop by category</a></li><li><a href="/collection/popular">Customer favourites</a></li><li><a href="/collections">Our collections</a></li><li><a href="/saved">Saved favourites</a></li></ul></div><div><h3>Here to help</h3><ul><li><a href="/delivery-and-returns">Delivery & collection</a></li><li><a href="/delivery-and-returns#returns">Returns & product help</a></li><li><a href="/contact-callus">Contact us</a></li><li><a href="/account-callus">My account</a></li></ul></div><div><h3>Come and say hello</h3><p>Mqabba Road, Siġġiewi<br>SGW 2600, Malta<br><a href="tel:+35699995135">+356 9999 5135</a><br><a href="mailto:info@callusgardencentre.com">info@callusgardencentre.com</a></p></div></div><div class="cg-footer-bottom"><span>© Callus Garden Centre · Blooming Garden Ltd</span><span><a href="/privacy-callus">Privacy & cookies</a> &nbsp; · &nbsp; Prices in EUR</span></div></div></footer>'''

def block(id,element='div',html=None,cls='',children=None,attrs=None):
    b={'blockId':'cg-'+id,'blockName':id.replace('-',' ').title(),'element':element,'baseStyles':{},'mobileStyles':{},'tabletStyles':{},'attributes':attrs or {},'classes':cls.split(),'children':children or []}
    if html is not None:b['innerHTML']=html
    return b

def sectionheading(eyebrow,title,href,label):
    return f'<div><p class="cg-eyebrow">{eyebrow}</p><h2>{title}</h2></div><a class="cg-link" href="{href}">{label} {arrow}</a>'

hero=block('hero','section',cls='cg-hero',children=[
    block('hero-copy',cls='cg-hero-copy',children=[block('hero-eyebrow','p','GROW A LITTLE HAPPINESS','cg-eyebrow'),block('hero-title','h1','Good things<br>start with<br><em>something green.</em>'),block('hero-introduction','p','A new leaf. A favourite corner. A garden full of possibility. Find your next little joy at Callus.','cg-intro'),block('hero-button','a','Explore the shop '+arrow,'cg-btn',attrs={'href':'/store'})]),
    block('hero-photo',cls='cg-hero-media',children=[block('hero-image','img',attrs={'src':'/assets/webshop/callus/garden-hero.webp','alt':'Garden inspiration: lush foliage and terracotta pots in a sunlit Mediterranean courtyard','width':'1536','height':'1024','fetchpriority':'high'}),block('hero-caption',html='<span>ROOM TO GROW. SPACE TO BREATHE.</span><span>THE CALLUS EDIT</span>',cls='cg-hero-caption')])])
home=[hero,block('benefits',html=f'<div>{leaf}<span>Plants for every kind of space</span></div><div>{location}<span>Your garden centre in Siġġiewi</span></div><div>{user}<span>A little advice, whenever you need it</span></div>',cls='cg-benefits'),block('categories-section','section',cls='cg-wrap cg-section',children=[block('categories-heading',html=sectionheading('FIND YOUR KIND OF GREEN','What will you grow?','/categories','Explore all'),cls='cg-section-heading'),block('category-cards',cls='cg-category-grid',attrs={'data-category-grid':''})]),block('popular-section','section',cls='cg-tinted',children=[block('popular-content',cls='cg-wrap cg-section',children=[block('popular-heading',html=sectionheading('LOVED BY OUR CUSTOMERS','The everyday favourites.','/collection/popular','Shop favourites'),cls='cg-section-heading'),block('popular-cards',cls='cg-products',attrs={'data-popular-grid':''})])]),block('editorial','section',cls='cg-editorial',children=[block('editorial-photo',html='<img src="/assets/webshop/callus/garden-hero.webp" alt="Mediterranean garden inspiration with herbs and terracotta pots" width="768" height="512" loading="lazy">',cls='cg-editorial-photo'),block('editorial-copy',cls='cg-editorial-copy',children=[block('editorial-eyebrow','p','A SMALL SPACE. A FRESH START.','cg-eyebrow'),block('editorial-title','h2','Your own little<br>corner of green.'),block('editorial-intro','p','A sunny balcony, a quiet courtyard, a windowsill with potential. You don’t need a big garden to grow something good.','cg-editorial-description'),block('editorial-button','a','Find your inspiration '+arrow,'cg-btn cg-btn-light',attrs={'href':'/collection/balcony'})])]),block('feature-section','section',cls='cg-wrap cg-section',children=[block('feature-heading',html=sectionheading('A LITTLE OUT OF THE ORDINARY','Make room for something special.','/collection/statement','Discover more'),cls='cg-section-heading'),block('feature-cards',cls='cg-products',attrs={'data-featured-grid':''})]),block('promises-section','section',cls='cg-wrap cg-section',attrs={'style':'border-top:1px solid var(--line)'},children=[block('promises',html=f'<div>{leaf}<h3>For the love of growing.</h3><p>From the first leaf to the finishing touch, discover plants and garden essentials for everyday living.</p></div><div>{user}<h3>A friendly place to start.</h3><p>New to plants or planning your next project? Ask our team for help finding what works for you.</p></div><div>{location}<h3>Rooted in Malta.</h3><p>Visit Callus Garden Centre on Mqabba Road, Siġġiewi. There’s always something to discover.</p></div>',cls='cg-promise-grid')])]
contact='''<div class="cg-wrap"><div class="cg-breadcrumb"><a href="/shop">Home</a> / Visit & contact</div><div class="cg-page-heading"><h1>Let’s grow something good.</h1><p>Choosing a plant, planning a garden or looking for something special? We’re here to help.</p></div><div class="cg-help-layout"><div class="cg-contact-card"><h2>Come and say hello.</h2><p>Callus Garden Centre<br>Mqabba Road, Siġġiewi<br>SGW 2600, Malta</p><p><a href="tel:+35699995135">+356 9999 5135</a><br><a href="mailto:info@callusgardencentre.com">info@callusgardencentre.com</a></p><a class="cg-btn" href="https://www.google.com/maps/search/?api=1&query=Callus+Garden+Centre+Mqabba+Road+Siggiewi+Malta" target="_blank" rel="noopener">Get directions ↗</a><p class="cg-note" style="margin-top:20px">Please call to confirm current opening hours before travelling.</p></div><div class="cg-faq"><h2>A little help, right here.</h2><details open><summary>Can you help me choose a plant?</summary><p>Of course. Tell us about the space, available light and what you’d like to grow. Our team can help you explore the options.</p></details><details><summary>Can I check availability before visiting?</summary><p>Please call with the product name or code. Availability can change throughout the day.</p></details><details><summary>Can I arrange delivery?</summary><p>Contact us with your location and the products you have in mind. We will confirm arrangements and any charge before you order.</p></details></div></div></div>'''
delivery='''<div class="cg-wrap"><div class="cg-breadcrumb"><a href="/shop">Home</a> / Delivery & product help</div><div class="cg-page-heading"><h1>Good things, handled with care.</h1><p>Here’s how to get help with delivery, collection and your purchase.</p></div><div class="cg-help-layout"><div class="cg-faq"><details open><summary>Delivery in Malta</summary><p>Delivery arrangements depend on your location and the products selected. Contact our team to confirm availability, timing and any delivery charge before placing an order.</p></details><details open><summary>Collection from the garden centre</summary><p>Please contact us to confirm your items and agree a collection time at Callus Garden Centre, Mqabba Road, Siġġiewi.</p></details><details id="returns" open><summary>Returns or a problem with a product</summary><p>Contact our team with your receipt or order reference and a description of the issue. For damaged products, photographs can help us understand what happened. We will explain the next steps for your purchase.</p></details><details><summary>Plants and product photographs</summary><p>Living plants vary naturally in shape, height and colour. Check the product name for pot size and other specifications. Decorative pots are included only where stated.</p></details></div><div class="cg-contact-card"><h2>Let’s work it out.</h2><p>If you have a question about your purchase, speak to our team.</p><p><a href="tel:+35699995135">+356 9999 5135</a><br><a href="mailto:info@callusgardencentre.com">info@callusgardencentre.com</a></p><a class="cg-btn" href="/contact-callus">Contact Callus →</a></div></div></div>'''
account='''<div class="cg-wrap"><div class="cg-breadcrumb"><a href="/shop">Home</a> / My account</div><div class="cg-page-heading"><h1>Welcome back.</h1><p>A little easier to pick up where you left off.</p></div><div class="cg-help-layout"><div class="cg-contact-card"><h2>Your Callus account</h2><p>Sign in with your existing shop account to access your account and orders.</p><a class="cg-btn" href="/login?redirect-to=%2Fshop">Sign in to my account →</a></div><div><h2>Just here to browse?</h2><p>Explore the shop, save your favourites and build your basket without an account.</p><a class="cg-link" href="/store">Continue exploring →</a><p class="cg-note" style="margin-top:25px">Need help with an existing account? Contact our team.</p></div></div></div>'''
privacy='''<div class="cg-wrap"><div class="cg-breadcrumb"><a href="/shop">Home</a> / Privacy & cookies</div><div class="cg-page-heading"><h1>Your privacy matters.</h1></div><div class="cg-page-body"><h2>About this test storefront</h2><p>This is the Callus Garden Centre UAT website. When online checkout is enabled, we store your contact details, address and order in our shop system to process your purchase. Stripe handles card details on its secure payment page. In Stripe test mode, no real money is taken.</p><h2>Basket and saved favourites</h2><p>The storefront uses your browser’s local storage to remember your basket and saved products. These are specific to this browser. You can remove individual products or clear them through your browser’s site-data settings.</p><h2>Site services</h2><p>The existing shop platform may set session cookies and collect server logs. Website fonts are loaded from Google Fonts. The final production privacy and cookie notice, including the shop’s account, order, payment and analytics processing, must be reviewed before launch.</p><h2>Contact</h2><p>For questions about your information, contact Blooming Garden Ltd at <a href="mailto:info@callusgardencentre.com">info@callusgardencentre.com</a>.</p></div></div>'''

pages=[('callus_all_products','callus-all-products','all-products','store','Shop plants & garden essentials'),('landing_page','landing-page','shop','home','Plants, pots & little joys'),('all_products','all-products','store','store','Shop plants & garden essentials'),('categories','categories','categories','categories','Shop by category'),('category','category','category/:name','category','Discover your kind of green'),('collections','collections','collections','collections','Thoughtful collections'),('collection','collection','collection/:name','collection','The Callus edit'),('products_details','products-details','item/:item_code','product','Product details'),('cart','cart','cart','basket','Your basket'),('callus_checkout','callus-checkout','checkout','checkout','Guest checkout'),('callus_saved','callus-saved','saved','saved','Your saved favourites'),('callus_contact','callus-contact','contact-callus','contact','Visit & contact Callus'),('callus_delivery','callus-delivery','delivery-and-returns','delivery','Delivery & product help'),('callus_account','callus-account','account-callus','account','My account'),('callus_privacy','callus-privacy','privacy-callus','privacy','Privacy & cookies')]

def build():
    for kind,extension in [('css','css'),('js','js')]:
        name='callus-storefront-'+kind;folder=DEST/'client_scripts'/name.replace('-','_');folder.mkdir(parents=True,exist_ok=True)
        (folder/(name.replace('-','_')+'.json')).write_text(json.dumps({'doctype':'Builder Client Script','modified':RELEASE['modified'],'name':name,'script_type':{'css':'CSS','js':'JavaScript'}[kind],'script':(APP/'public/callus'/('storefront.'+extension)).read_text()},indent=1)+'\n')
    data_script=(APP/'callus_storefront/data_script.py').read_text()
    for directory,name,route,kind,title in pages:
        folder=DEST/'pages'/directory;folder.mkdir(parents=True,exist_ok=True)
        content=home if kind=='home' else [block(kind+'-content',html={'contact':contact,'delivery':delivery,'account':account,'privacy':privacy}.get(kind,'<div class="cg-wrap cg-section"><p>Loading your next favourite…</p><noscript>Please enable JavaScript to browse the catalogue, or call +356 9999 5135.</noscript></div>'))]
        root=block('root','body',cls='cg-app',attrs={'data-page':kind},children=[block('header',html=header),block('main','main',children=content,attrs={'id':'cg-main'}),block('footer',html=footer),block('catalogue-data','script',html='{{ catalogue | tojson }}',attrs={'id':'cg-catalogue','type':'application/json'})])
        root['blockId']='root'
        doc={'doctype':'Builder Page','modified':RELEASE['modified'],'name':name,'page_name':name,'page_title':title,'route':route,'published':1,'is_standard':1,'app':'webshop','project_folder':'webshop','authenticated_access':0,'dynamic_route':int(':' in route),'page_data_script':data_script,'disable_indexing':0,'blocks':[root],'head_html':'<meta name="theme-color" content="#244c3a"><meta name="color-scheme" content="light">','body_html':'','meta_description':'Discover plants, pots, garden essentials and thoughtful gifts at Callus Garden Centre in Siġġiewi, Malta.','client_scripts':[{'builder_script':'callus-storefront-css'},{'builder_script':'callus-storefront-js'}]}
        (folder/(directory+'.json')).write_text(json.dumps(doc,indent=1,ensure_ascii=False)+'\n')
        (folder/'data_script.py').write_text(data_script)
    print('Built',len(pages),'Builder pages and 2 shared scripts.')
if __name__=='__main__':build()
